language: node_js
node_js:
 - node

script:
 - npm run build

before_deploy:
 - npm run dist

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master

cache:
  directories:
    - node_modules

