language: node_js
node_js:
  - node

install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;

script:
  - npm run build

before_deploy:
  - npm run dist

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master

cache:
  directories:
    - node_modules
